---
title: "HKR6000_Assign1"
author: "Becky Maher"
date: "13/02/2020"
output:
    html_document:
      keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Creating a Dataset 

## Dataset 1

# ID

```{r}

ID <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14")

```

# Coach

```{r}

coach1 <- c("5", "5", "N/A", "4", "4", "3", "5", "4", "5", "2", "5", "5", "5", "2")
coach2 <- c("3", "5", "5", "4", "5", "4", "5", "4", "5", "5", "4", "5", "2", "3")
coach3 <- c("5", "5", "2", "3", "4", "4", "5", "4", "4", "4", "5", "5", "5", "5")
coach4 <- c("4", "5", "2", "3", "4", "4", "5", "5", "N/A", "4", "5", "5", "5", "4")
coach5 <- c("5", "5", "4", "4", "4", "4", "5", "4", "4", "4", "5", "4", "5", "2")
coach6 <- c("5", "4", "5", "2", "5", "4", "5", "4", "5", "5", "5", "5", "4", "3")

```

# Program

```{r}

program1 <- c("4", "4", "4", "3", "4", "2", "2", "3", "2", "4", "3", "5", "5", "4")
program2 <- c("5", "4", "5", "5", "5", "3", "5", "3", "4", "5", "5", "4", "3", "5")
program3 <- c("4", "5", "N/A", "3", "5", "2", "5", "5", "3", "2", "3", "1", "4", "2")
program4 <- c("5", "5", "5", "5", "5", "4", "5", "5", "4", "4", "4", "5", "4", "3")
program5 <- c("4", "5", "5", "3", "5", "4", "5", "5", "2", "3", "4", "3", "5", "5")
program6 <- c("5", "5", "5", "5", "5", "2", "5", "5", "4", "3", "4", "4", "5", "4")

```

```{r}

dataset_1 <- data.frame(ID, coach1, coach2, coach3, coach4, coach5, coach6, program1, program2, program3, program4, program5, program6)

```

## Dataset 2

```{r}

facilities1 <-c("5", "5", "3", "4", "5", "3", "4", "2", "N/A", "4", "3", "5", "4", "3")
facilities2 <-c("3", "5", "2", "5", "5", "5", "4", "5", "N/A", "4", "4", "4", "3", "5")
facilities3 <-c("4", "5", "5", "3", "5", "5", "5", "4", "N/A", "5", "5", "4", "4", "5")
facilities4 <-c("5", "5", "5", "5", "5", "5", "5", "4", "N/A", "4", "4", "5", "5", "5")

```

```{r}

overall <- c("4", "N/A", "4", "4", "5", "4", "5", "5", "5", "5", "5", "5", "5", "5")

```

```{r}

gender <- c("male", "male", "female", "male", "female", "male", "male", "female", "male", "male", "female", "female", "male", "male")

```


```{r}

coach <- c("1", "4", "2", "N/A", "5", "1", "4", "1", "3", "1", "4", "3", "5", "2")

```

```{r}

fitness1_1 <- c("30", "15", "18", "29", "24", "17", "21", "18", "24", "16", "28", "14", "31", "23")
fitness1_2 <- c("35", "25", "28", "30", "N/A", "26", "36", "31", "32", "27", "39", "N/A", "34", "32")
fitness2_1 <- c("4", "2", "3", "4", "5", "2", "3", "2", "3", "2", "4", "2", "5", "3")
fitness2_2 <- c("6", "4", "4", "5", "N/A", "4", "4", "5", "3", "4", "6", "N/A", "6", "5")
fitness3_1 <- c("7", "4", "3", "5", "5", "4", "4", "3", "5", "3", "6", "4", "4", "4")
fitness3_2 <- c("10", "6", "5", "5", "N/A", "5", "7", "6", "6", "6", "8", "N/A", "8", "6")

```

```{r}
dataset_2 <- data.frame(ID, facilities1, facilities2, facilities3, facilities4, overall, gender, coach, fitness1_1, fitness1_2, fitness2_1, fitness2_2, fitness3_1, fitness3_2)
```

## Save as csv

```{r}
setwd("/Users/beckymaher/Desktop/Graduate degree/")
```
```{r}

write_csv(dataset_1, "/Users/beckymaher/Desktop/graduate degree/HKR6000/dataset_1.csv")

write_csv(dataset_2, "/Users/beckymaher/Desktop/graduate degree/HKR6000/dataset_2.csv")

```

